[platformio]
default_envs = retrofit
src_dir = .

# pio run -t upload -e retrofit
[env:retrofit]
build_flags =
    -std=gnu++17
; -DDEV_WIFI_SSID=\"Beeline-16\"  
  ;  -DDEV_WIFI_PASSWORD=\"trubataburetka\"
   ;-DREAL_TEMP_SENSOR -- add when thermostat connected
   ;-DREAL_IR          -- add when IR emiiter connected
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-0001
build_src_filter =
    +<thermohub/main.cpp>
    +<logger.cpp>
    +<time/*.cpp>
    +<hub/*.cpp>
    +<diagnostics/*.cpp>
    +<scheduler/*.cpp>
    +<app/adaptive_thermostat_tuning.cpp>
    +<app/pid_thermostat_controller.cpp>
    ; +<app/thermostat_controller.cpp> -- add when thermostat connected 
lib_deps =
    bblanchon/ArduinoJson@^6.21.0
    tzapu/WiFiManager @ ^2.0.17
    ; paulstoffregen/OneWire --for thermostat 
    ; milesburton/DallasTemperature --for thermostat 
   
# pio test -e test_desktop
[env:test_desktop]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -std=gnu++17
build_src_filter =
    +<IRSender.cpp>
    +<IRReciever.cpp>
    +<protocol.cpp>
    +<logger.cpp>
    +<time/*.cpp>
    +<app/retrofit_controller.cpp>
    +<app/pid_thermostat_controller.cpp>
    +<app/adaptive_thermostat_tuning.cpp>
    +<app/room_temp_sensor.cpp>
    +<hub/hub_receiver.cpp>
    +<hub/hub_connectivity.cpp>
    +<hub_additions/hub_mock_scheduler.cpp>
    +<hub_additions/hub_ai_insights.cpp>
    +<scheduler/*.cpp>
    +<heater/heater.cpp>
    +</test/test_native/test_main.cpp>


; # pio run -t upload -e heater
; [env:heater]
; platform = espressif32
; framework = arduino
; board = esp32dev
; monitor_speed = 115200
; build_flags =
;    -std=gnu++17
;    -DREAL_OLED
; build_src_filter =
;     +<heater/*.cpp>
;     +<IRReciever.cpp>
;     +<protocol.cpp>
;     +<logger.cpp>
;     +<time/*.cpp>
;     -<app/*.cpp>
;     -<hub/*.cpp>
;     -<scheduler/*.cpp>
; lib_deps =
;     ; adafruit/Adafruit SSD1306
;     ; adafruit/Adafruit GFX Library

