[platformio]
default_envs = retrofit
src_dir = .

[env]
build_flags =
    -std=gnu++17

# pio run -t upload -e retrofit
[env:retrofit]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200
build_src_filter =
    +<src/main.cpp>
    +<logger.cpp>
    +<time/*.cpp>
    +<hub/*.cpp>
    
lib_deps =
    bblanchon/ArduinoJson@^6.21.0
    knolleary/PubSubClient@^2.8
